// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5zINSDlzZJO0DiL2AAVJbiqxksLJZf00',
    appId: '1:835578640169:web:47d37536e72c92244ae938',
    messagingSenderId: '835578640169',
    projectId: 'insta-9e966',
    authDomain: 'insta-9e966.firebaseapp.com',
    storageBucket: 'insta-9e966.appspot.com',
    measurementId: 'G-9N1KNH6XPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXw8r3JYjS3IEO5KyyrJ2rzJ5aLbpH36I',
    appId: '1:835578640169:android:b126fb09634202464ae938',
    messagingSenderId: '835578640169',
    projectId: 'insta-9e966',
    storageBucket: 'insta-9e966.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwusenBzswMNGyjs4ZyPlFEYomO_ckZ_g',
    appId: '1:835578640169:ios:544ac400b42468d74ae938',
    messagingSenderId: '835578640169',
    projectId: 'insta-9e966',
    storageBucket: 'insta-9e966.appspot.com',
    iosClientId: '835578640169-5o439j0jf9delpcjpcc506ijhfg1ckal.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwusenBzswMNGyjs4ZyPlFEYomO_ckZ_g',
    appId: '1:835578640169:ios:c2b247f52c81141c4ae938',
    messagingSenderId: '835578640169',
    projectId: 'insta-9e966',
    storageBucket: 'insta-9e966.appspot.com',
    iosClientId: '835578640169-nlq84t5st6nctlpcekndeuni3hp9stke.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram.RunnerTests',
  );
}
